from typing import Optional
from sqlmodel import Field, SQLModel
from datetime import datetime, timezone

def utc_now_naive():
    return datetime.now(timezone.utc).replace(tzinfo=None)

class AuthProfile(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    platform: str
    display_name: str
    storage_ref: str
    status: str = Field(default="Active")
    last_checked_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=utc_now_naive)

class Tracker(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    tracker_type: str = Field(description="URL, KEYWORD, ACCOUNT")
    target: str = Field(description="Target URL, Keyword string, or Account name")
    tier: int = Field(default=1, description="Fallback tier for direct URLs (1: RSS, 2: MD, 3: Agentic)")
    radar_section: str = Field(description="Custom section name (e.g. Frontier Outpost, Geek Radar, etc.)")
    is_active: bool = Field(default=True)
    fetch_interval_minutes: int = Field(default=30)
    prompt_override: Optional[str] = Field(default=None, description="Custom instructions for LLM extraction")
    cookie_string: Optional[str] = Field(default=None, description="[DEPRECATED] Optional cookie string. Use AuthProfile instead.")
    source_intent: str = Field(default="RSS_FEED", description="RSS_FEED, KEYWORD_DISCOVERY, ACCOUNT_TRACKING, HYBRID")
    fetch_policy: Optional[str] = Field(default=None, description="JSON policy overrides")
    auth_profile_id: Optional[int] = Field(default=None, foreign_key="authprofile.id", description="Auth Profile reference")
    normalized_intent: Optional[str] = Field(default=None, description="JSON string caching intent definition mapping")
    created_at: datetime = Field(default_factory=utc_now_naive)
    last_scraped_at: Optional[datetime] = None

class RawArticle(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    tracker_id: int = Field(foreign_key="tracker.id")
    title: str
    url: str = Field(unique=True, index=True)
    content: str = Field(description="Raw text or HTML extracted from the page")
    published_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=utc_now_naive)
    processed: bool = Field(default=False, description="Whether it has been processed by LLM")

class IntelReport(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    raw_article_id: int = Field(foreign_key="rawarticle.id", unique=True)
    source_url: str
    validity_category: str = Field(description="[SPAM], [MALICIOUS_LINK], [VALID_NEWS]")
    radar_section: str = Field(description="Inherited from Tracker section")
    llm_summary: str
    importance_score: int = Field(default=0, description="1 to 5")
    original_content_hash: str = Field(description="Hash for anti-poisoning signature")
    created_at: datetime = Field(default_factory=utc_now_naive)
    shared: bool = Field(default=False, description="Whether it has been pushed to the central server")
    key_entities: str = Field(default="[]", description="JSON list of extracted entities")
    event_timestamp: Optional[str] = Field(default=None, description="ISO8601 string of the actual event/publish time extracted by LLM")

class TrendAlert(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    entity_name: str = Field(index=True)
    alert_summary: str
    related_article_ids: str = Field(description="Comma separated IntelReport IDs")
    created_at: datetime = Field(default_factory=utc_now_naive)

class PipelineStatus(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    tracker_name: str = Field(description="Name of the tracker being processed")
    action_type: str = Field(description="e.g., 'Scraping', 'AI Processing'")
    detail: str = Field(description="Details of the current operation")
    updated_at: datetime = Field(default_factory=utc_now_naive)

class DailyBriefing(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    date_str: str = Field(index=True, description="YYYY-MM-DD")
    section_name: str = Field(default="ALL", description="Target section, or ALL for comprehensive")
    content: str = Field(description="Synthesized briefing generated by Gemini")
    created_at: datetime = Field(default_factory=utc_now_naive)

class TokenUsage(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    model_name: str
    action_type: str
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    created_at: datetime = Field(default_factory=utc_now_naive)

class Subscription(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    target_url: str = Field(unique=True, index=True)
    is_active: bool = Field(default=True)
    fetch_interval_minutes: int = Field(default=60)
    diff_policy: Optional[str] = Field(default=None, description="JSON policy overrides for page diff")
    normalized_intent: Optional[str] = Field(default=None, description="JSON string caching intent definition mapping")
    created_at: datetime = Field(default_factory=utc_now_naive)
    last_scraped_at: Optional[datetime] = None
    last_status: str = Field(default="Idle")

class PageSnapshot(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    subscription_id: int = Field(foreign_key="subscription.id")
    content_hash: str
    content_text: str
    created_at: datetime = Field(default_factory=utc_now_naive)

class SubscriptionUpdate(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    subscription_id: int = Field(foreign_key="subscription.id")
    diff_text: str
    is_read: bool = Field(default=False)
    llm_summary: Optional[str] = None
    created_at: datetime = Field(default_factory=utc_now_naive)

class InvestigationRecord(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    query: str
    native_result: Optional[str] = None
    funnel_result: Optional[str] = None
    created_at: datetime = Field(default_factory=utc_now_naive)

class SchemaVersion(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    version_id: str = Field(unique=True, index=True)
    applied_at: datetime = Field(default_factory=utc_now_naive)

class TaskRequest(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    job_type: str = Field(description="e.g. SCRAPE, PROCESS, TREND_SCAN, BRIEFING")
    target_type: Optional[str] = Field(default=None, description="e.g. TRACKER, SECTION")
    target_id: Optional[str] = Field(default=None, description="Tracker ID, or Section Name, or null")
    payload: Optional[str] = Field(default=None, description="JSON string of additional arguments")
    status: str = Field(default="PENDING", description="PENDING, RUNNING, COMPLETED, FAILED")
    retry_count: int = Field(default=0, description="Number of times this task was retried")
    max_retries: int = Field(default=3, description="Maximum retry limit")
    created_at: datetime = Field(default_factory=utc_now_naive)
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    error: Optional[str] = None

class PipelineRun(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    tracker_id: Optional[int] = Field(default=None, foreign_key="tracker.id", nullable=True)
    subscription_id: Optional[int] = Field(default=None, foreign_key="subscription.id", nullable=True)
    status: str = Field(default="RUNNING") # RUNNING, SUCCESS, FAILED
    normalized_intent: Optional[str] = Field(default=None, description="JSON representing normalized intent mapping snapshot")
    started_at: datetime = Field(default_factory=utc_now_naive)
    finished_at: Optional[datetime] = None
    total_routes: int = Field(default=0)
    total_items: int = Field(default=0)
    accepted_items: int = Field(default=0)
    error_summary: Optional[str] = None
    cost_flag_browser: bool = Field(default=False)
    cost_flag_llm: bool = Field(default=False)

class PipelineEvent(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    run_id: int = Field(foreign_key="pipelinerun.id")
    step_index: int = Field(description="Sequence step number (1-indexed)")
    created_at: datetime = Field(default_factory=utc_now_naive)
    stage: str = Field(description="RESOLVE, FETCH, DEDUPLICATE, LLM_FILTER, SAVE")
    route_id: Optional[str] = None
    adapter: Optional[str] = None
    input_data: Optional[str] = None # Masked/desensitized target snippet
    output_summary: Optional[str] = None # Text snippet/length/hash summary (max 100 chars)
    status: str = Field(default="SUCCESS") # SUCCESS, FAILED
    duration_ms: int = Field(default=0)
    error: Optional[str] = None
