from typing import Optional
from sqlmodel import Field, SQLModel
from datetime import datetime, timezone

class Source(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    url: str
    tier: int = Field(default=1, description="1: Basic RSS, 2: Alternative Frontend, 3: Agentic Scraper")
    radar_section: str = Field(description="Custom section name (e.g. Frontier Outpost, Geek Radar, AI Art, etc.)")
    is_active: bool = Field(default=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_scraped_at: Optional[datetime] = None

class RawArticle(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="source.id")
    title: str
    url: str = Field(unique=True, index=True)
    content: str = Field(description="Raw text or HTML extracted from the page")
    published_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    processed: bool = Field(default=False, description="Whether it has been processed by LLM")

class IntelReport(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    raw_article_id: int = Field(foreign_key="rawarticle.id", unique=True)
    source_url: str
    validity_category: str = Field(description="[SPAM], [MALICIOUS_LINK], [VALID_NEWS]")
    radar_section: str = Field(description="Inherited from Source section")
    llm_summary: str
    importance_score: int = Field(default=0, description="1 to 5")
    original_content_hash: str = Field(description="Hash for anti-poisoning signature")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    shared: bool = Field(default=False, description="Whether it has been pushed to the central server")
    key_entities: str = Field(default="[]", description="JSON list of extracted entities")
    event_timestamp: Optional[str] = Field(default=None, description="ISO8601 string of the actual event/publish time extracted by LLM")

class TrendAlert(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    entity_name: str = Field(index=True)
    alert_summary: str
    related_article_ids: str = Field(description="Comma separated IntelReport IDs")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class PipelineStatus(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    source_name: str = Field(description="Name of the source being processed")
    action_type: str = Field(description="e.g., 'Scraping', 'AI Processing'")
    detail: str = Field(description="Details of the current operation")
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class DailyBriefing(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    date_str: str = Field(unique=True, index=True, description="YYYY-MM-DD")
    content: str = Field(description="Synthesized briefing generated by Gemini 1.5 Pro")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class TokenUsage(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    model_name: str
    action_type: str
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
